#!/usr/bin/env python

Import("env")
Import("env_modules")

env_spout = env_modules.Clone();

thirdparty_obj = []

# thirdparty_dir = "#thirdparty/SPOUTSDK/SpoutLibrary/"
# # thirdparty_dir = "#thirdparty/SPOUTSDK/SpoutLibrary/Binaries/x64/"
# thirdparty_sources = [
#     "SpoutLibrary.cpp"
#     # "SpoutLibrary.h"
# ]
# thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

# env_spout.Prepend(CPPPATH=[thirdparty_dir, thirdparty_dir + ""])

# env_thirdparty = env_spout.Clone()
# env_thirdparty.disable_warnings()
# env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
# env.modules_sources += thirdparty_obj

module_obj = []
env_spout.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# env.Append(LIBPATH=["#thirdparty/SPOUTSDK/SpoutLibrary/Binaries/x64/"])
# env.Append(LIBS=File("C:\\Users\\theaz\\dev\\godot\\thirdparty\\SPOUTSDK\\SpoutLibrary\\Binaries\\x64\\SpoutLibrary.lib"))
env.Append(LIBS=File("#thirdparty/SPOUTSDK/SpoutLibrary/Binaries/x64/SpoutLibrary.lib"))

env.Depends(module_obj, thirdparty_obj)
